image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  user: timetracker
  password: changeme
  database: timetracker

service:
  port: 5432

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""
